### ISSUE TITLE
App crashed.

### ISSUE THREAD

**Issue by Chrupek121** [dima123493/AirlinesManagerTycoonHelper_Selenide#1]
Hello,
I tried running your script, and it was working smoothly until a certain point. The problem occurs when the script tries to execute one of the audits in sequence. I have a feeling that some overlay appears there, preventing the OK button from being pressed. Maybe adding a handler could help?

`org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Connection reset
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(Unknown Source)
        at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by dima123493** [comment]
Hi, thank you for creating this issue! I will investigate it and try to come up with a solution in upcoming updates.

**Comment by dima123493** [comment]
The mistake is done by your IDEA or connection, not because of the code. Try to update IDEA and rerun or use another development environment, it supposes to work. 
Have a nice day!
